---
abstract: 'Serviço de Rastreamento de Objetos (Brazilian Postal Object Tracking Service)'
author:
  - 'Breno G. de Oliveira <garu@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WWW-Correios-SRO
no_index:
  directory:
    - t
    - inc
requires:
  Class::XSAccessor: '1.05'
  Exporter: '0'
  HTML::TreeBuilder: '0'
  LWP::UserAgent: '0'
  Test::More: '0.88'
  URI::file: '0'
  parent: '0'
  utf8: '0'
version: '0.09'
