--- #YAML:1.0
name:               WWW-Correios-SRO
version:            0.01
abstract:           Serviço de Rastreamento de Objetos (Brazilian Postal Object Tracking Service)
author:
    - Breno G. de Oliveira <garu@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::XSAccessor:  1.05
    Exporter:           0
    HTML::TreeBuilder:  0
    LWP::UserAgent:     0
    parent:             0
    Test::More:         0.88
    URI::file:          0
    utf8:               0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
